### ISSUE TITLE
Project template build error

### ISSUE THREAD

**Issue by kafram** [eclipse-emfcloud/modelserver-glsp-integration#51]
Hi all, 

I've tried to build this project template (/modelserver-glspjava-emf-theia), and I getting some error messages related to "Too long filename". 

Searching for a solution, I found that this limitation (255 chars on filename) is on linux filesystem.

Does anyone know what I can do to fix this?

Best regards,

Carlos.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for org.eclipse.emfcloud.integration.example.parent 0.7.0-SNAPSHOT:
[INFO] 
[INFO] org.eclipse.emfcloud.integration.example.parent .... SUCCESS [  0.113 s]
[INFO] org.eclipse.emfcloud.integration.example.modelserver FAILURE [ 33.298 s]
[INFO] org.eclipse.emfcloud.integration.example.glspjavaserver SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.506 s
[INFO] Finished at: 2023-03-07T11:24:11-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.googlecode.addjars-maven-plugin:addjars-maven-plugin:1.0.5:add-jars (default) on project org.eclipse.emfcloud.integration.example.modelserver: Failed to install artifact org.eclipse.emfcloud.modelserver.glsp:org.eclipse.emfcloud.integration.example.modelserver-org.eclipse.emfcloud.modelserver.glsp.notation.commands-0.7.0-SNAPSHOT.jar:jar:0.7.0-SNAPSHOT: /home/carlos/.m2/repository/org/eclipse/emfcloud/modelserver/glsp/org.eclipse.emfcloud.integration.example.modelserver-org.eclipse.emfcloud.modelserver.glsp.notation.commands-0.7.0-SNAPSHOT.jar/0.7.0-**SNAPSHOT/org.eclipse.emfcloud.integration.example.modelserver-org.eclipse.emfcloud.modelserver.glsp.notation.commands-0.7.0-SNAPSHOT.jar-0.7.0-SNAPSHOT.jar (Nome de arquivo muito longo) -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.eclipse.emfcloud.integration.example.modelserver
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ndoschek** [comment]
We will continue to investigate the problem in the emfcloud discussion https://github.com/eclipse-emfcloud/emfcloud/discussions/201#discussioncomment-5231519 until the problem can be tracked down.

**Comment by ndoschek** [comment]
Closing, as the issue could be resolved (please see https://github.com/eclipse-emfcloud/emfcloud/discussions/201#discussioncomment-5245607)
